name: calculator
description: Simply a calculator
version: 1.0.1+2
repository: https://github.com/withcenterdev5/calculator

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
